# Generated by Django 6.0.3 on 2026-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lesson_practice_challenge_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('amazon', 'Amazon'), ('udemy', 'Udemy'), ('codecademy', 'Codecademy'), ('merch', 'Merchandise'), ('other', 'Other')], default='other', max_length=20)),
                ('cta_label', models.CharField(default='View', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'abstract': False,
            },
        ),
    ]
