# Generated by Django 6.0.3 on 2026-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='best_for',
            field=models.CharField(blank=True, help_text='Shown as "Best for: <value>", e.g. "Beginner Programmers".', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='details_url',
            field=models.URLField(blank=True, help_text='Optional link to a longer write-up. Leave blank to hide the Details button.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
