# Generated by Django 6.0.3 on 2026-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_resource_best_for_resource_details_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, upload_to='resources/'),
        ),
    ]
