# Generated by Django 6.0.3 on 2026-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_engagementevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('lesson_view', 'Lesson view'), ('code_run', 'Code run'), ('quiz_view', 'Quiz view'), ('page_view', 'Page view'), ('affiliate_click', 'Affiliate click'), ('ai_usage', 'AI usage')], max_length=32),
        ),
    ]
