# Generated by Django 6.0.3 on 2026-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lesson_challenge_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='challenge_expected_output',
            field=models.TextField(blank=True, help_text='Exact output the learner must produce to auto-complete the lesson.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='challenge_starter_code',
            field=models.TextField(blank=True, help_text='Starter code for the inline mini-challenge editor. Falls back to starter_code when blank.'),
        ),
    ]
